# Generated by Django 2.2.10 on 2020-10-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201011_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='topic',
        ),
    ]
