# Generated by Django 2.2.10 on 2020-10-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201011_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Разедел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='tagarticle',
            options={'verbose_name': 'Тематика статьи'},
        ),
    ]
