# Generated by Django 2.2.10 on 2020-10-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201011_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagarticle',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика статьи'},
        ),
        migrations.RenameField(
            model_name='tagarticle',
            old_name='is_main',
            new_name='main',
        ),
    ]
